<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-18T03:26:53 EDT" name="Default suite" finished-at="2023-04-18T03:27:07 EDT" duration-ms="14822">
    <groups>
    </groups>
    <test started-at="2023-04-18T03:26:53 EDT" name="Default test" finished-at="2023-04-18T03:27:07 EDT" duration-ms="14822">
      <class name="Login_TestCases.Login_testcases">
        <test-method is-config="true" signature="setup()[pri:0, instance:Login_TestCases.Login_testcases@449a4f23]" started-at="2023-04-18T03:26:53 EDT" name="setup" finished-at="2023-04-18T03:26:54 EDT" duration-ms="1536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Testcase01_ValidEmail_And_VALIDPassword()[pri:1, instance:Login_TestCases.Login_testcases@449a4f23]" started-at="2023-04-18T03:26:54 EDT" name="Testcase01_ValidEmail_And_VALIDPassword" finished-at="2023-04-18T03:27:00 EDT" duration-ms="6263" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase01_ValidEmail_And_VALIDPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Login_TestCases.Login_testcases@449a4f23]" started-at="2023-04-18T03:27:00 EDT" name="tearDown" finished-at="2023-04-18T03:27:01 EDT" duration-ms="195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Login_TestCases.Login_testcases@449a4f23]" started-at="2023-04-18T03:27:01 EDT" name="setup" finished-at="2023-04-18T03:27:01 EDT" duration-ms="799" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Testcase02_InValidEmail_And_validPassword()[pri:2, instance:Login_TestCases.Login_testcases@449a4f23]" started-at="2023-04-18T03:27:01 EDT" name="Testcase02_InValidEmail_And_validPassword" finished-at="2023-04-18T03:27:07 EDT" duration-ms="5792" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at Login_TestCases.Login_testcases.Testcase02_InValidEmail_And_validPassword(Login_testcases.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase02_InValidEmail_And_validPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Login_TestCases.Login_testcases@449a4f23]" started-at="2023-04-18T03:27:07 EDT" name="tearDown" finished-at="2023-04-18T03:27:07 EDT" duration-ms="183" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Login_TestCases.Login_testcases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
